[tasks.build]
run = "CARGO_PROFILE_DEV_DEBUG=false cargo build"
alias = "b"

[tasks.build-debug]
run = "CARGO_PROFILE_DEV_DEBUG=true cargo build"
alias = "bd"

[tasks.build-release]
run = "cargo build --release"
alias = "br"

[tasks.run]
usage = '''
arg "[args]" var=#true
'''
run = "CARGO_PROFILE_DEV_DEBUG=false cargo run --bin json-editor -- ${usage_args}"
alias = "r"

[tasks.run-debug]
usage = '''
arg "[args]" var=#true
'''
run = "CARGO_PROFILE_DEV_DEBUG=true cargo run --bin json-editor -- ${usage_args}"
alias = "rd"

[tasks.run-release]
usage = '''
arg "[args]" var=#true
'''
run = "cargo run --bin json-editor --release ${usage_args}"
alias = "rr"

[tasks.run-example]
run = "CARGO_PROFILE_DEV_DEBUG=false cargo run --example demo"
alias = "re"

[tasks.run-example-debug]
run = "CARGO_PROFILE_DEV_DEBUG=true cargo run --example demo"
alias = "red"

[tasks.run-example-release]
run = "cargo run --example demo --release"
alias = "rer"

[tasks.test]
run = "CARGO_PROFILE_DEV_DEBUG=false cargo test"
alias = "t"

[tasks.test-debug]
run = "CARGO_PROFILE_DEV_DEBUG=true cargo test"
alias = "td"

[tasks.test-release]
run = "cargo test --release"
alias = "tr"

[tasks.fmt]
run = "cargo fmt"
alias = "f"
